### ISSUE TITLE
Code out-of-date relative to `hmac-drbg` crate?

### ISSUE THREAD

**Issue by tarcieri** [ethereumproject/hmac-drbg-rs#1]
Hello!

I work on https://github.com/RustCrypto. I was interested in sending a PR to bump the versions of various RustCrypto dependencies this crate uses, but it seems this repo is out-of-date as compared to the https://crates.io/crates/hmac-drbg crate?

Is this the correct repo for the `hmac-drbg` crate? If so, it seems the changes made in v0.2.0 and v0.3.0 are missing from this repo.

**Comment by splix** [comment]
Hi @tarcieri 

The author continued the work at https://github.com/sorpaas/rust-hmac-drbg.

Thank you for bringing it up, it seems that I'll need to archive the project and update the links
